stages:
  - build
  - test
  - publish
  - deploy

variables:
  # Caminhos do projeto
  SOLUTION_PATH: "ProdutoGW.sln"
  BUILD_CONFIGURATION: "Release"
  BUILD_OUTPUT_DIR: "bin/Release/net7.0"
  CONNECTION_STRING: "Server=localhost\\SQLEXPRESS;Database=ProdutoDB;User Id=sa;Password=xpto@123;TrustServerCertificate=True"

before_script:
  # Instalação do .NET SDK no runner
  - 'echo "Configuring .NET SDK environment"'
  - 'apt-get update && apt-get install -y apt-transport-https'
  - 'curl -sSL https://dotnet.microsoft.com/download/dotnet/thank-you/dotnet-sdk-7.0.100-linux-x64-installer | bash'
  - 'dotnet --version'

# Etapa de Build
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - 'dotnet restore $SOLUTION_PATH'
    - 'dotnet build $SOLUTION_PATH --configuration $BUILD_CONFIGURATION'
  only:
    - develop

# Etapa de Testes Unitários
unit_tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - 'dotnet test $SOLUTION_PATH --configuration $BUILD_CONFIGURATION --filter "FullyQualifiedName~ProdutoGW.Tests" --logger "trx;LogFileName=unit_tests_results.trx"'
  artifacts:
    paths:
      - unit_tests_results.trx
  only:
    - develop

# Etapa de Testes de Integração
integration_tests:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - 'dotnet test $SOLUTION_PATH --configuration $BUILD_CONFIGURATION --filter "FullyQualifiedName~ProdutoGW.IntegrationTests" --logger "trx;LogFileName=integration_tests_results.trx"'
  artifacts:
    paths:
      - integration_tests_results.trx
  only:
    - develop

# Etapa de Publicação
publish:
  stage: publish
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - 'dotnet publish $SOLUTION_PATH --configuration $BUILD_CONFIGURATION --output $BUILD_OUTPUT_DIR'
  artifacts:
    paths:
      - $BUILD_OUTPUT_DIR
  only:
    - develop

# Etapa de Deploy
deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - 'echo "Starting deployment process..."'
    - 'echo "Copying files to server or executing deploy scripts here."'
    # Adicione comandos para envio de arquivos ou execução de scripts no servidor de destino.
  only:
    - develop
