trigger:
  branches:
    include:
      - main   # Alvo do branch principal para deploy

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToAzure
  displayName: 'Deploy to Azure App Service'
  steps:

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'drop'
      downloadPath: '$(Build.SourcesDirectory)'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'your-azure-subscription'  # Configuração do seu Azure
      appName: 'your-app-service-name'               # Nome do seu Azure App Service
      package: '$(Build.SourcesDirectory)/drop/*.zip'