trigger:
- develop  # Disparar o pipeline na branch 'develop'

pool:
  vmImage: 'windows-latest'  # Usar a imagem do Windows mais recente (não paralelizado)

variables:
  solution: 'ProdutoGW.sln'  # Caminho para o arquivo de solução
  buildConfiguration: 'Release'  # Configuração de build
  buildPlatform: 'Any CPU'  # Plataforma do build
  buildOutput: '$(Build.ArtifactStagingDirectory)'  # Diretório de saída dos artefatos
  dbConnectionString: 'Server=localhost\\SQLEXPRESS;Database=ProdutoDB;User Id=sa;Password=xpto@123;TrustServerCertificate=True'  # String de conexão com o banco de dados

jobs:
- job: BuildAndTest  # Job único para build e testes
  pool:
    vmImage: 'ubuntu-latest'  # Especificando o ambiente do agente
  steps:

    # Etapa de restore (restaurar dependências)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'  # Restaurar dependências para todos os projetos .csproj