trigger:
  branches:
    include:
      - main   # Alvo do branch principal para build

pool:
  vmImage: 'ubuntu-latest'   # Usando a imagem Ubuntu para CI

variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'  # Versão do .NET SDK, caso esteja utilizando .NET 6

  - task: Restore@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: Build@1
    inputs:
      solution: '**/*.sln'
      configuration: $(buildConfiguration)

  - task: Test@2
    inputs:
      testSelector: 'testAssemblies'
      testAssembly: '**/*Tests*.dll'  # Execute todos os testes no projeto

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'
      publishLocation: 'Container'
