trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/ProdutoGW.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  connectionString: 'Server=localhost\\SQLEXPRESS;Database=ProdutoDB;User Id=sa;Password=xpto@123;TrustServerCertificate=True'

steps:

# Etapa de build
- task: MSBuild@1
  inputs:
    solution: $(solution)
    arguments: '/p:Configuration=$(buildConfiguration)'
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)

# Etapa de testes unitários
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Testes de integração 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'



